### PR TITLE
feat/LandingPage bug fix

### PR DESCRIPTION
**Pull request by dikshab0202**
JIRA - https://issues.newrelic.com/browse/NR-3156
Description: Bug Fix such as alignments, font related css.

*******
chrome
*******
image

image

*******
FireFox
*******
image

image

### CODE REVIEW

**Comment by aswanson-nr** [comment]
Hey @dikshab0202, we fixed the issue with the fonts, so if you pull in the latest from the feature branch the preview should work just fine!

**Comment by dikshab0202** [comment]
> Hey @dikshab0202, we fixed the issue with the fonts, so if you pull in the latest from the feature branch the preview should work just fine!

Hi @aswanson-nr , Thanks for updating, latest pull has been taken.
With some changes such as dashboard carousal and margin, padding and other css fix , I pushed the code, can you please review and approve it or if any suggestion, please let me know.

**Comment by aswanson-nr** [comment]
Hey @dikshab0202, this has a lot of conflicts on it. You probably just need to merge in the feature branch to get those cleared up. I _think_ most of these issues have been addressed on the feature branch, so merging that in should clear up a lot of the bugs in that ticket.

**Comment by dikshab0202** [comment]
Hi @aswanson-nr , I was on leave. In my absence, another PR has already been raised -> https://github.com/newrelic/instant-observability-website/pull/156

**Pull request closed without merging**
