### PR TITLE
applied font urls instead of static files

### PR DESCRIPTION
**Pull request by pkosanam**
JIRA: https://issues.newrelic.com/browse/NR-10900
Description: applied font urls instead of static files

### CODE REVIEW

**Comment by aswanson-nr** [comment]
Hey @pkosanam, do we also want to delete the other font files?

**Comment by pkosanam** [comment]
> 

I have added CDN url for the font and then I have deleted the respective .otf file from the repo.

As I don't have CDN url for the other fonts, I have not yet deleted them from the repo.

**Comment by aswanson-nr** [comment]
Hey @pkosanam, It appears to be failing to load the fonts because of an access control header. 
Screen Shot 2022-05-17 at 11 53 51 AM
I'm guessing that has to do with the fact that it's on a preview, I'm guessing the access is locked to newrelic.com

**Comment by aswanson-nr** [comment]
Although I'm also getting a 403 for the fonts if I try to fetch them from the newrelic.com domain.
Screen Shot 2022-05-17 at 11 58 43 AM

**Comment by pkosanam** [comment]
Hi @aswanson-nr ,

After having a chat with @LizBaker , here is her comment on the aws urls
image

**Comment by pkosanam** [comment]
Note:
I have checked the gatsby url of docs website and observed that the fonts are not loading on their gatsby url too.
gatsby url of docs website: https://docswebsite-dailyrelease51822evening.gtsb.io/
image

**Comment by aswanson-nr** [comment]
No longer applicable, we are pulling fonts from the theme

**Pull request closed without merging**
