### PR TITLE
Update sign-up buttons in footer

### PR DESCRIPTION
**Pull request by zstix**
## Description
This will update the buttons in the "Get started today" footer to use the semantic-token-style class names and colors for the "primary" and "primary-accent" buttons.

Previously, the buttons were a slightly different color. Furthermore, they didn't have the correct hover treatment.

## Related Issue(s)
* NR-5642

## Screenshot(s)
Screen Shot 2022-05-09 at 16 57 39

### CODE REVIEW

**Comment by aswanson-nr** [comment]
I could be wrong, but I think the design wants the button text color to match the background green color.

**Comment by zstix** [comment]
Sure does! I made an executive decision to match our internal style guide and semantic tokens. I plan on running it by our designer later tonight.

**Comment by aswanson-nr** [comment]
Hey @zstix, did you get a confirmation on this change?

**Comment by zstix** [comment]
Yeah!

**Review by aswanson-nr — APPROVED** [review]

**Pull request merged**
